spring:
  profiles:
    active: dev
  application:
    name: guitar-backend
  # DataSource Config
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/mpguitar?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
#  # session ????????
#  session:
#    timeout: 86400
#    store-type: redis
  # 2.7 ?????kni4j
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
#  # redis ??
#  redis:
#    port: 6379
#    host: localhost
#    database: 1
server:
  port: 8080
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete # ????????????(since 3.3.0,????????????2)
      logic-delete-value: 1 # ??????(??? 1)
      logic-not-delete-value: 0 # ??????(??? 0)

